# Generated by Django 4.1.3 on 2022-11-21 04:06

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
