# Generated by Django 4.1.3 on 2022-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ratio',
            field=models.FloatField(default=-1),
        ),
    ]
