# Generated by Django 4.1.3 on 2022-11-21 03:57
import random

from django.contrib.auth.models import User as AdminUser
from django.db import migrations
from django.utils import timezone
from faker import Faker

from backend.models import *

fake = Faker()
Faker.seed(123)


def fake_avatar():
    return f"https://picsum.photos/seed/${fake.md5()}/150/150"


def populate(apps, schema_editor):
    AuthUser: AdminUser = apps.get_model("auth", "User")

    def create_user(username, first_name, last_name, description, password="123"):
        auth_user = AuthUser.objects.create_user(
            username=username,
            email=fake.email(),
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        base_user = BaseUser.objects.get(id=auth_user.id)
        user = User(base_user=base_user, description=description, avatar=fake_avatar()).save()
        return user

    im = create_user(
        username='im',
        first_name="Ian",
        last_name="Malcolm",
        description="Should've stayed in the car."
    )

    er = create_user(
        username="er",
        first_name="Ellen",
        last_name="Ripley",
        description="Lvl 6 rating. Pilot."
    )

    pt = create_user(
        username="pt",
        first_name="Peregrin",
        last_name="Took",
        description="Home is behind, the world ahead... " +
                    "And there are many paths to tread. Through shadow, to the edge of night, " +
                    "until the stars are all alight... Mist and shadow, cloud and shade, " +
                    "all shall fade... all... shall... fade... "
    )

    rk = create_user(
        username="rk",
        first_name="Rey",
        last_name="Kenobi",
        description="Excited to be here!"
    )

    al = create_user(
        username="al",
        first_name="April",
        last_name="Ludgate",
        description="Witch"
    )

    jo = create_user(
        username="jo",
        first_name="John",
        last_name="Ousterhout",
        description="<i>CS142!</i>",
    )

    users = [im, er, pt, rk, al, jo]

    for u in users:
        u.follower = [f for f in random.sample(users, 4) if f.id != u.id]
        u.following = [f for f in random.sample(users, 4) if f.id != u.id]
        u.save()

    def parse_time(time):
        return timezone.make_aware(datetime.strptime(time, "%Y-%m-%d %H:%M:%S"))

    Photo(
        date_time=parse_time("2012-08-30 10:44:23"),
        file_name="ouster.jpg",
        user=jo,
        comments=[Comment(date_time=parse_time("2012-09-02 14:01:00"),
                          comment="Learning new programming languages is hard... it's so easy to forget a </div>!",
                          user=jo),
                  Comment(date_time=parse_time("2013-09-06 14:02:00"),
                          comment="This is another comment, with a bit more text; " +
                                  "if the text gets long enough, does it wrap properly " +
                                  "from line to line?",
                          user=jo),
                  Comment(date_time=parse_time("2013-09-08 14:06:00"),
                          comment="If you see this text in <b>boldface</b> " +
                                  "then HTML escaping isn't working properly.",
                          user=jo)
                  ]
    ).save()

    Photo(
        date_time=parse_time("2009-09-13 20:00:00"),
        file_name="malcolm2.jpg",
        user=im,
        comments=[Comment(
            date_time=parse_time("2009-09-14 18:07:00"),
            comment="If there is one thing the history of evolution has" +
                    " taught us it's that life will not be contained. Life breaks " +
                    "free, it expands to new territories and crashes through " +
                    "barriers, painfully, maybe even dangerously, but, uh... well, " +
                    "there it is. Life finds a way.",
            user=im),
        ]
    ).save()

    Photo(
        date_time=parse_time("2009-09-13 20:05:03"),
        file_name="malcolm1.jpg",
        user=im,
        comments=[]
    ).save()

    Photo(
        date_time=parse_time("2013-11-18 18:02:00"),
        file_name="ripley1.jpg",
        user=er,
        comments=[]
    ).save()

    Photo(
        date_time=parse_time("2013-09-20 17:30:00"),
        file_name="ripley2.jpg",
        user=er,
        comments=[
            Comment(date_time=parse_time("2013-11-28 17:45:13"),
                    comment="Back from my trip. Did IQs just... drop sharply while I was away?",
                    user=er)
        ]
    ).save()

    Photo(
        date_time=parse_time("2009-07-10 16:02:49"),
        file_name="kenobi1.jpg",
        user=rk,
        comments=[]
    ).save()

    Photo(
        date_time=parse_time("2010-03-18 23:48:00"),
        file_name="kenobi2.jpg",
        user=rk,
        comments=[
            Comment(date_time=parse_time("2013-11-02 14:07:00"),
                    comment="Hey Rey, great form. Love what " +
                            "you do with the scavenged tech, got any tips?",
                    user=er),
            Comment(date_time=parse_time("2013-11-02 14:07:00"),
                    comment="Definitely! I love your work! I'm away on a trip at " +
                            "the moment, but let's meet up when I get back! :)",
                    user=rk),
        ]
    ).save()

    Photo(
        date_time=parse_time("2010-08-30 14:26:00"),
        file_name="kenobi3.jpg",
        user=rk,
        comments=[
            Comment(date_time=parse_time("2010-09-06 13:59:33"),
                    comment="Made a new friend today! Well, they followed me home, anyway.",
                    user=rk)
        ]
    ).save()

    Photo(
        date_time=parse_time("2013-12-03 09:02:00"),
        file_name="took1.jpg",
        user=pt,
        comments=[
            Comment(date_time=parse_time("2016-01-04 2:00:01"),
                    comment="Which one are you?", user=al),
            Comment(date_time=parse_time("2016-01-04 2:04:01"),
                    comment="The tall one", user=pt),
        ]
    ).save()

    Photo(
        date_time=parse_time("2013-12-03 09:03:00"),
        file_name="took2.jpg",
        user=rk,
        comments=[
            Comment(date_time=parse_time("2013-12-04 13:12:00"),
                    comment="What do you mean you haven't heard of second breakfast?",
                    user=pt)
        ]
    ).save()

    Photo(
        date_time=parse_time("2013-09-04 09:16:32"),
        file_name="ludgate1.jpg",
        user=al,
        comments=[
            Comment(date_time=parse_time("2013-09-04 10:14:32"),
                    comment="Beautiful yet cold and aloof. Loner. Does not obey, " +
                            "occasionally chooses to cooperate. ",
                    user=al)
        ]
    ).save()

    Photo(
        date_time=parse_time("2008-10-16 17:12:28"),
        file_name="kenobi4.jpg",
        user=rk,
        comments=[
            Comment(date_time=parse_time("2008-10-16 18:04:55"),
                    comment="Wouldn't get anywhere without this beauty! " +
                            "Completely built from scraps by hand, but she goes at top " +
                            "speeds that'll rival any First Order piece of junk.",
                    user=rk),
        ]
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
