# Generated by Django 4.1.3 on 2023-01-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_photo_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file_name',
            new_name='file',
        ),
    ]
