# Generated by Django 4.1.3 on 2023-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_file_name_photo_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-date_time'], name='backend_pho_date_ti_6c521b_idx'),
        ),
    ]
