# Generated by Django 4.1.3 on 2022-12-23 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
