# Generated by Django 4.1.3 on 2022-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_phototag_photo_description_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
