# Generated by Django 4.1.3 on 2022-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
